apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
spec:
  selector:
    name: colegio-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 4200
  type: LoadBalancer

---

apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: colegio-app
  labels:
    name: colegio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: colegio-app
  template:
    metadata:
      labels:
        name: colegio-app
    spec:
      containers:
      - name: frontend
        image: frontend-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4200
      - name: backend
        image: backend-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000