kind: Service
apiVersion: v1
metadata:
  name: backend-service
  labels:
    name: backend-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: backend-app
  type: LoadBalancer

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: backend-app
  labels:
    name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-app
  template:
    metadata:
      labels:
        name: backend-app
    spec:
      containers:
        - name: backend
          image: backend-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000