 
version: '2'
services:
    redis:
    image: 'redis:4.0.11'
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
      - mongo
    command: ["./wait_for_it.sh", "--", "npm", "start"]